### ISSUE TITLE
Interaction of new `where` argument with `miceadds`

### ISSUE THREAD

**Issue by stefvanbuuren** [alexanderrobitzsch/miceadds#1]
Dear Alexander, 

I am currently working on a new argument to the `mice` function, called `where`, which allows the user to specify which cells to impute. There is a develop branch at my account (https://github.com/stefvanbuuren/mice/tree/where/R). 

One of the consequences is that I need to extend all univariate imputation functions with a `wy` argument. I've been careful not to break any existing code, but I've found that functions `mice.impute.2lonly.pmm` and `mice.impute.2lonly.norm` became dysfunctional. The problem is that `wy` cannot be passed if there is a multilevel structure, and needs to be broken down into classes, just like you did with `ry`. I have fixed both functions, but it might be that the behaviour may also show up in similar functions you incorporated into `miceadds`. Would you mind taking a look at whether this indeed the case, and see whether my solution could also be used in `miceadds`? 

I have not been able to include the `wy` argument into `mice.impute.2l.pan` since I would need to overwrite (part of) the data in `y1` before entering `pan`. Any ideas how to fix that?

Best wishes, Stef.

**Comment by alexanderrobitzsch** [comment]
Dear Stef,

I looked a bit in your code and it seems to be that one can overwrite `ry` by `wy` if a user requests. In the `2lonly` functions, the data is aggregated to the higher level and it is also done for `ry`. If would do the same for `wy`. 

I wonder whether one could work with the following pseudo-code

`# input ry and wy`
`if ( ! is.null(wy) ){  ry <- ! wy  }`

Could you correct me if I am wrong?
Best,
Alexander

**Comment by alexanderrobitzsch** [comment]
> I have not been able to include the wy argument into mice.impute.2l.pan since I would need to overwrite > (part of) the data in y1 before entering pan. Any ideas how to fix that?

I am afraid that it is not really possible to include `wy` in `2l.pan` imputation function. Could not one produce a warning message that the `wy` argument does not work for the `2l.pan`method?
