### ISSUE TITLE
micombine.cor with Fisher transform?

### ISSUE THREAD

**Issue by ESPoppelaars** [alexanderrobitzsch/miceadds#10]
Hi there,

Just a quick question: since Rubin's rules assume normality, pooling correlations first requires a transformation towards normality using Fisher Z transformation (Schafer, 1997)), and a subsequent backtransformation after pooling. Is this already incorporated in the micombine.cor function, or should I do this manually?

Thanks in advance!

Best regards,
Eefje Poppelaars

**Comment by alexanderrobitzsch** [comment]
Yes, the Fisher transformation is conducted in `micombine.cor`. I will include this information in the manual.

Alexander

**Comment by ESPoppelaars** [comment]
Great, thank you for your quick reply!
