### ISSUE TITLE
groupwise imputation with ml.lmer?

### ISSUE THREAD

**Issue by sophiestallasch** [alexanderrobitzsch/miceadds#12]
Hello, 

I was wondering whether the bygroup-function can be combined with the ml.lmer-function defined in miceadds. I want to perform groupwise imputation by means of three-level models.

Thank you in advance!

Kind regards,
Sophie Stallasch

**Comment by alexanderrobitzsch** [comment]
It was indeed a bug that the imputation method `ml.lmer` was not compatible within imputation method `bygroup`. The bug should have been fixed in `miceadds 2.15-6`.

**Comment by sophiestallasch** [comment]
Thank you very much! Now it works fine.
Kind regards.
