### ISSUE TITLE
mice.impute.bygroup - outs of bounds

### ISSUE THREAD

**Issue by santsang** [alexanderrobitzsch/miceadds#15]
Hi

I ran the examples.  It works well.  When I tried mine... it got this message: 

utilError in x[, group_vname] : subscript out of bounds

Thank you very much for your advice.

Sandro

**Comment by alexanderrobitzsch** [comment]
Please provide with an example in order to check whether my code or your input is the problem (as usual for requesting help for R packages). Otherwise, I am not able to fix the possible problem.

**Comment by santsang** [comment]
Thanks for offering help.  The data are from a RCT trial.  I will be in trouble if I post it online.  Will giving you the str() output be okay?

Sandro

**Comment by alexanderrobitzsch** [comment]
Or could you send me a subdataset which replicates the problem via email? `str` does not seem to be sufficient.

**Comment by santsang** [comment]
Thanks Alex for offering help.  I have sent a subset of pseudo data to the email address you stated in the vignette.  I bet it would be okay to discuss the reason to benefit everyone here.  I guess the reason is about setting factor... and so.

**Comment by santsang** [comment]
Hi Alex

Here are the settings:

(ini <- mice(dat, maxit = 0)) 
(pred<-ini$pred)
(pred[,]<-0)
pred[,"id"]<-(-2)
pred["outcome","id"]<-(-2)
pred["outcome",-c(1,3)]<-1
pred["outcome",c("strataIV","time")]<-0
(meth<-ini$meth)
meth[c("outcome")] <- "2l.pmm"

BTW, you may also be interested to know that parlmice() "could not found" mice.impute.2l.pmm.  I then resolved the problem with doRNG.

Many thanks for your help.

Sandro

**Comment by alexanderrobitzsch** [comment]
I still do not see a model which includes the method `mice.impute.bygroup` which was meant to cause a problem. Please provide a full script and complete information. It is important to minimize the amount of time for coping with possible problems by always giving the information as requested. This means code, data (or some subdataset) which EXACTLY reproduces the bug for which you are requesting help.

>> BTW, you may also be interested to know that parlmice() "could not found" mice.impute.2l.pmm. I 
>> then resolved the problem with doRNG.

I think that is unrelated to `mice.impute.2l.pmm`. Again, provide a reproducable example if you think that is really an issue.

**Comment by santsang** [comment]
Hi Alex

Thank you very much for you reply.

According to the documentation, I would imagine that the rest of the codes should be:

meth["outcome"] <- "bygroup"
  # by initial specification of meth become redundant
group <- list( "outcome"="strataIV" )
imputationFunction <- list("outcome"="2l.pmm" )

imp <- mice::mice( dat, meth=meth, pred=pred,
            m=20, maxit=24, group=group, imputationFunction=imputationFunction )

Perhaps you may direct me the right coding...

Sandro

**Comment by alexanderrobitzsch** [comment]
I think that the issue was a mixture of problems. The warning message was caused by the fact that the grouping variable was not included in the predictorMatrix with a `1` entry. I changed this requirement in the recent update. Moreover, make sure that you do not include multicollinear predictors. The syntax now runs with the recent `miceadds` version.

```
dat <- utils::read.table( "miceGroup.csv", sep=";", dec=".", header=TRUE)

ini <- mice(dat, maxit = 0)
pred<-ini$pred
(pred[,]<-0)
pred[,"id"]<-(-2)
pred["outcome","id"]<-(-2)
pred["outcome",-c(1,3)]<-1
pred["outcome",c("strataIV","time")]<-0
meth<-ini$meth
meth["outcome"] <- "bygroup"
group <- list( "outcome"="strataIV" )
imputationFunction <- list("outcome"="2l.pmm" )
# remove these columns to avoid multocollinearity of variables
pred[, c("gender","TX")] <- 0
# impute
imp <- mice::mice(dat, method=meth, predictorMatrix=pred, imputationFunction=imputationFunction,
                group=group, m=1, maxit=2)
```

**Comment by santsang** [comment]
Thanks for your help.  I will try tomorrow.  Sandro
