### ISSUE TITLE
not able to impute using ml.lmer in v 3.3?

### ISSUE THREAD

**Issue by nmenon2** [alexanderrobitzsch/miceadds#17]
I'm trying to impute missing values in Level 1 and Level 2 variables using the ml.lmer command which was working in miceadds v(3.2), but keeps throwing an error since the update yesterday. 

Error message :
Error in check.method(method = method, data = data, where = where, blocks = blocks,  :  The following functions were not found: mice.impute.ml.lmer, mice.impute.ml.lmer

How can I resolve this?

**Comment by alexanderrobitzsch** [comment]
I do not really think that there is an issue. I tried the examples in the manual and did not observe (and I did not expect) amy issue. Please check whether
a) ``miceadds`` is correctly installed
b) whether you loaded ``miceadds``

**Comment by nmenon2** [comment]
Will try again. The same error was thrown when I used the datlist2mids command.  Strangely, the code works when I use the previous version of miceadds.

**Comment by alexanderrobitzsch** [comment]
I do not believe so. a) or b) are options. I would strongly suggest to use ``miceadds::datlist2mids(...)`` instead of ``datlist2mids(...)`` because in the former case you do not have to run ``library(miceadds)`` in advance.
