### ISSUE TITLE
Check on 2.10-11 fails

### ISSUE THREAD

**Issue by stefvanbuuren** [alexanderrobitzsch/miceadds#2]
I can install version 2.10-11 (2018-01-22) by `devtools::install_github("alexanderrobitzsch/miceadds")`, but if I try to check in Rstudio or `Clean and Rebuild`, I get a `cpp` related error. Any idea whether I am doing something wrong?

    * installing *source* package ‘miceadds’ ...
    ** libs
    clang++  -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -    RcppExports.cpp:99:54: error: address of overloaded function 'ma_pmm6_C' does not match required type 'void *()'
    {"ma_pmm6_C",                         (DL_FUNC) &ma_pmm6_C,                         6},
                                                     ^~~~~~~~~
    RcppExports.cpp:90:17: note: candidate function has different number of parameters (expected 0 but has 6)
    RcppExport SEXP ma_pmm6_C(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
                ^
    RcppExports.cpp:52:21: note: candidate function has different number of parameters (expected 0 but has 6)
    Rcpp::NumericVector ma_pmm6_C(Rcpp::NumericVector y, Rcpp::NumericVector ry01,  Rcpp::NumericMatrix x, double ridge, Rcpp::NumericVector coefu1, Rcpp::NumericVector donorsample);
                    ^
    1 error generated.
    make: *** [RcppExports.o] Error 1
    ERROR: compilation failed for package ‘miceadds’

**Comment by alexanderrobitzsch** [comment]
I am not able to replicate the bug (admittedly, I do not use Rstudio for package building). I did a CRAN check of the recent package version and did not obtain errors.

**Comment by stefvanbuuren** [comment]
OK, thanks. Will try to fiddle around it.

**Comment by stefvanbuuren** [comment]
On `miceadds 2.11-77` I still get 

    * installing *source* package ‘miceadds’ ...
    ** libs
    clang++  -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Users/buurensv/Library/R/3.4/library/Rcpp/include"  I"/Users/buurensv/Library/R/3.4/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
    RcppExports.cpp:733:77: error: address of overloaded function 'ma_pmm6_C' does not match required type 'void *()'
        {"ma_pmm6_C",                                                (DL_FUNC) &ma_pmm6_C,                                                 6},
                                                                                ^~~~~~~~~
    RcppExports.cpp:706:17: note: candidate function has different number of parameters (expected 0 but has 6)
    RcppExport SEXP ma_pmm6_C(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
                    ^
    RcppExports.cpp:461:21: note: candidate function has different number of parameters (expected 0 but has 6)
    Rcpp::NumericVector ma_pmm6_C(Rcpp::NumericVector y, Rcpp::NumericVector ry01, Rcpp::NumericMatrix x, double ridge, Rcpp::NumericVector coefu1, Rcpp::NumericVector donorsample);
                        ^
    1 error generated.
    make: *** [RcppExports.o] Error 1
    ERROR: compilation failed for package ‘miceadds’
    * removing ‘/Users/buurensv/Package/miceadds/miceadds.Rcheck/miceadds’
 
I am on Mac OS 10.13.4. Will also check CRAN version.

**Comment by stefvanbuuren** [comment]
Updated my development environment, but still no luck with the CRAN version:

    R CMD check miceadds_2.10-14.tar.gz

gives the same error.

**Comment by alexanderrobitzsch** [comment]
Could you check whether the package TAM can be installed? I want to figure out whether it is a specific issue with the pmm function. Did you made a recent update of Rcpp and RcppArmadillo?

**Comment by alexanderrobitzsch** [comment]
I think that I have found the possible cause of the bug. I uploaded a new version miceadds 2.11-80.

**Comment by stefvanbuuren** [comment]
Great, that solves it. The C sources now compile.
