### ISSUE TITLE
datlist2mids fails after subsetting if factors don't still contain all levels

### ISSUE THREAD

**Issue by jwilliman** [alexanderrobitzsch/miceadds#20]
I encountered the following error when trying to subset a `mids` object that contain factor levels. If some of the factors levels are missing after subsetting then the resulting `datlist` object cannot be converted back to a `mids` object. This is particularly a problem if the subsetting variable is itself a factor. Is there a way around this? 

``` r

library(miceadds)
#> Loading required package: mice
#> Loading required package: lattice
#> 
#> Attaching package: 'mice'
#> The following objects are masked from 'package:base':
#> 
#>     cbind, rbind
#> * miceadds 3.7-6 (2019-12-15 13:38:43)
data(nhanes2)
nhanes2_imp  <- mice(nhanes2, seed = 12345, printFlag = FALSE)
nhanes2_list <- mids2datlist(nhanes2_imp)
nhanes2_sub  <- subset_datlist(nhanes2_list, subset = nhanes2$age == "20-39")
datlist2mids(nhanes2_sub)
#> Error in Ops.factor(left, right): level sets of factors are different
```

<sup>Created on 2020-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by alexanderrobitzsch** [comment]
Fixed in ``miceadds`` 3.8-8 which is at Github and hopefully soon at CRAN.
