### ISSUE TITLE
pooling error with nested imputations 

### ISSUE THREAD

**Issue by flh3** [alexanderrobitzsch/miceadds#21]
Hello! I was trying out using nested multiple imputations in `miceadds`. I was able to get the imputation to run but when I run the pooling function, I get an error. This example is taken directly from the example in the `mice.nmi` function:

```
library(BIFIEsurvey)
data(data.timss2, package="BIFIEsurvey" )
datlist <- data.timss2
# remove first four variables
M <- length(datlist)
for (ll in 1:M){
  datlist[[ll]] <- datlist[[ll]][, -c(1:4) ]
}

#***************
# (1) nested multiple imputation using mice
imp1 <- miceadds::mice.nmi(datlist,  m=3, maxit=2 )
summary(imp1)

#***************
# (2) first linear regression: ASMMAT ~ migrant + female
res1 <- with( imp1, stats::lm(ASMMAT ~ migrant + female ) ) # fit
pres1 <- miceadds::pool.mids.nmi(res1)  # pooling
```

The error that appears after running the pooling function is: 

```
> Error in dimnames(qhat) <- `*vtmp*` : 
> length of 'dimnames' [3] must match that of 'dims' [2]
```
I've tried using the github version as well as the CRAN version with the same results. 

Thanks for any help you can provide.

Best,
Francis

**Comment by alexanderrobitzsch** [comment]
Thank you for reporting the bug. The issue seems to be caused by internal changes of ``mice::pool()``. I fixed the code and upload a bugfix in ``miceadds 3.12-6`` in some minutes on Github.

Best,
Alexander
