### ISSUE TITLE
Is it possible to convert mids objects to an Amelia object?

### ISSUE THREAD

**Issue by atanasj** [alexanderrobitzsch/miceadds#26]
As per the issue title... I'm wondering if this is possible in the current version of this package, or if there would be potential utility to a feature like this?

**Comment by alexanderrobitzsch** [comment]
Maybe this would not be too difficult to create and I already thought about this feature when working on the different conversion functions of multiple imputation objects. I include the feature on my to-do list with a time frame of one month for working on it.

**Comment by alexanderrobitzsch** [comment]
I created a simple function ``datlist2Amelia`` in the recent Github miceadds dev version which will be updated today.
