### ISSUE TITLE
warning message when using datalist2mids

### ISSUE THREAD

**Issue by sdaza** [alexanderrobitzsch/miceadds#4]
When using `datalist2mids` I get this warning:  

```
library(data.table)
library(miceadds)
library(Amelia)
library(readr)
file = 'https://raw.githubusercontent.com/sdaza/lambda/master/notebooks/chile.csv'

data = data.table(read_csv(file))

vars = c('water', 'sewage', 'elec')
i = which(names(data) %in% vars)
bounds = cbind(i, rep(0, length(i)), rep(100, length(i)))

imp1 = amelia(as.data.frame(data), 
              bounds = bounds, 
              m=5, # only five!
              ts = 'year', cs = 'ctry', 
              splinetime = 4, intercs = TRUE,  
              p2s = 0, 
              logs=c('igdp_pc', 'iurban', 'ilit', 'itfr','Ex', 'water', 'sewage', 'elec'), 
              lags = c('igdp_pc', 'Ex', 'iurban', 'itfr', 'ilit'), 
              leads = c('Ex', 'igdp_pc', 'iurban', 'itfr', 'ilit'),
              empri = .01*nrow(data))

imputations = datalist2mids(imp1$imputations)

Warning message in data.matrix(x):
“NAs introduced by coercion”Warning message in data.matrix(x):
“NAs introduced by coercion”
```

**Comment by alexanderrobitzsch** [comment]
Am 24.04.2018 um 21:07 schrieb Sebastian Daza:
> When using `datalist2mids` I get warnings:
> 
> ```
> library(data.table)
> library(miceadds)
> library(Amelia)
> library(readr)
> file = 'https://raw.githubusercontent.com/sdaza/lambda/master/notebooks/chile.csv'
> 
> data = data.table(read_csv(file))
> 
> vars = c('water', 'sewage', 'elec')
> i = which(names(data) %in% vars)
> bounds = cbind(i, rep(0, length(i)), rep(100, length(i)))
> 
> imp1 = amelia(as.data.frame(data),
>                bounds = bounds,
>                m=5, # only five!
>                ts = 'year', cs = 'ctry',
>                splinetime = 4, intercs = TRUE,
>                p2s = 0,
>                logs=c('igdp_pc', 'iurban', 'ilit', 'itfr','Ex', 'water', 'sewage', 'elec'),
>                lags = c('igdp_pc', 'Ex', 'iurban', 'itfr', 'ilit'),
>                leads = c('Ex', 'igdp_pc', 'iurban', 'itfr', 'ilit'),
>                empri = .01*nrow(data))
> 
> imputations = datalist2mids(imp1$imputations)
> 
> Warning message in data.matrix(x):
>   “NAs introduced by coercion”Warning message in data.matrix(x):
> ```
> 

I think that the error messages can be ignored. They are caused by an 
internal evaluation of mice::mice(..., m=0) which does an "empty" 
imputation to create an object of class mids. If all character variables 
in the dataset would be changed to factors, the warning would disappear.

Alexander
