### ISSUE TITLE
Cannot execute "subset_datlist(expr_subset = ())"

### ISSUE THREAD

**Issue by rouninnomi** [alexanderrobitzsch/miceadds#5]
Hello, I really enjoy data analysis with you fantastic packages. 
I've been trying to subset mids object by an expression. 

_**imp: a mids object produced by parlMICE, SBP_ER: a variable of original data.frame indicating systolic blood pressure in the ER department**_

`imp2 <- subset_datlist(imp, subset = (SBP_ER > 100))`

But, an error

`Error in subset_datlist(imp, subset = (SBP_ER > 100)) : 
  object 'SBP_ER' not found`

was shown.

I tried sample codes in your document, 

`data(data.ma02) ` 
`datlist1a <- data.ma02 `  
`datlist5a <- miceadds::subset_datlist( datlist1a ,  expr_subset = migrant == 1 )`

however, it also failed. 

`Error in miceadds::subset_datlist(datlist1a, expr_subset = migrant ==  : 
  object 'migrant' not found`

How should I do next?

**Comment by alexanderrobitzsch** [comment]
`subset` was not intended to operate on variables in a data frame. I did so because I wanted to retain the same number of cases in each imputed dataset. So I opted for something like `subset = datlist1a[[1]]migrant == 1` assuming that the variable `migrant` has no missing values in the datasets.

**Comment by rouninnomi** [comment]
Thank you. I implemented the intended execution via `mids2datlist()` and `lapply()` function.
